esphome:
  name: viewe-display-7inch
  friendly_name: "VIEWE 7-inch Touch Display"
  includes:
    - include/
  platformio_options:
    board_build.flash_mode: dio
    board_build.partitions: huge_app.csv
    build_flags:
      - "-DBOARD_HAS_PSRAM"
      - "-DLV_CONF_INCLUDE_SIMPLE"
      - "-DLV_COLOR_DEPTH=16"
      - "-DLV_COLOR_16_SWAP=0"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_SPIRAM_SUPPORT: "y"
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_SPIRAM_SPEED_80M: "y"
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "8192"
      CONFIG_LCD_ENABLE_DEBUG_LOG: "y"

logger:
  level: INFO
  logs:
    viewe_lvgl_display: DEBUG

api:
  encryption:
    key: "your-32-char-encryption-key-here!!"

ota:
  - platform: esphome
    password: "your-ota-password-here"

wifi:
  ssid: "Your-WiFi-SSID"
  password: "Your-WiFi-Password"
  ap:
    ssid: "VIEWE Display Fallback"
    password: "fallback123"

captive_portal:

web_server:
  port: 80

external_components:
  - source:
      type: local
      path: components
    components: [viewe_lvgl_display]

# Main display configuration with touch
viewe_lvgl_display:
  id: main_display
  width: 800
  height: 480
  
  # RGB display pins
  rgb_pins:
    red: [45, 48, 47, 21, 14]      # R0-R4
    green: [5, 6, 7, 15, 16, 4]    # G0-G5
    blue: [8, 3, 46, 9, 1]         # B0-B4
  
  # Display control pins
  control_pins:
    de_pin: 40
    vsync_pin: 41
    hsync_pin: 39
    pclk_pin: 42
  
  # Backlight
  backlight_pin: 2
  
  # Touch controller (GT911)
  touch:
    sda: 19
    scl: 20
    reset_pin: 38
    interrupt_pin: 18
    i2c_frequency: 400kHz

# Sensors
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    update_interval: 60s

  - platform: internal_temperature
    name: "ESP Temperature"
    update_interval: 60s

# Touch interrupt monitoring
binary_sensor:
  - platform: gpio
    pin:
      number: 18
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Touch Active"
    filters:
      - delayed_off: 100ms

  - platform: status
    name: "Device Status"

# Display backlight control
switch:
  - platform: gpio
    pin: 2
    name: "Display Backlight"
    restore_mode: RESTORE_DEFAULT_ON

# Control buttons
button:
  - platform: restart
    name: "Restart Device"
    
  - platform: safe_mode
    name: "Safe Mode"

# Time sync
time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Pacific/Auckland"