esphome:
  name: viewe-display-7inch
  friendly_name: "VIEWE 7-inch Touch Display"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_SPIRAM_SUPPORT: "y"
      CONFIG_SPIRAM_MODE_OCT: "y" 
      CONFIG_SPIRAM_SPEED_80M: "y"
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "8192"
      CONFIG_LCD_ENABLE_DEBUG_LOG: "y"

logger:
  level: DEBUG
  logs:
    viewe_display: DEBUG
    gt911: DEBUG

api:

ota:
  - platform: esphome
    password: "testpassword"

wifi:
  ssid: "TestNetwork"
  password: "testpass123"
  ap:
    ssid: "VIEWE Display Fallback"
    password: "fallback123"

captive_portal:

web_server:
  port: 80

# I2C bus for GT911 touchscreen
i2c:
  sda: 19
  scl: 20
  scan: true
  frequency: 400kHz

# Custom RGB display component
external_components:
  - source:
      type: local
      path: components
    components: [viewe_display]

# VIEWE RGB Display (proper ESPHome display platform)
display:
  - platform: viewe_display
    id: main_display
    width: 800
    height: 480
    # RGB pins matching working config
    red_pins: [14, 21, 47, 48, 45]
    green_pins: [4, 16, 15, 7, 6, 5]  
    blue_pins: [1, 9, 46, 3, 8]
    # Control pins
    de_pin: 40
    pclk_pin: 42
    hsync_pin: 39
    vsync_pin: 41
    # Optional pins
    backlight_pin: 2
    # Much higher timing values - closer to working RPI DPI config
    pixel_clock_frequency: 16MHz
    pclk_inverted: true
    hsync_idle_low: false
    vsync_idle_low: false
    de_idle_high: false
    hsync_pulse_width: 48
    hsync_back_porch: 40
    hsync_front_porch: 40
    vsync_pulse_width: 1
    vsync_back_porch: 31
    vsync_front_porch: 13
    update_interval: 3s  # Change color every 3 seconds
    lambda: |-
      // Color cycling test to verify pin mapping
      static int color_phase = 0;
      
      switch (color_phase % 8) {
        case 0:
          ESP_LOGI("display", "Filling screen RED");
          it.fill(Color(255, 0, 0));    // Pure Red
          break;
        case 1:
          ESP_LOGI("display", "Filling screen GREEN"); 
          it.fill(Color(0, 255, 0));    // Pure Green
          break;
        case 2:
          ESP_LOGI("display", "Filling screen BLUE");
          it.fill(Color(0, 0, 255));    // Pure Blue
          break;
        case 3:
          ESP_LOGI("display", "Filling screen YELLOW");
          it.fill(Color(255, 255, 0));  // Yellow (Red + Green)
          break;
        case 4:
          ESP_LOGI("display", "Filling screen MAGENTA");
          it.fill(Color(255, 0, 255));  // Magenta (Red + Blue)
          break;
        case 5:
          ESP_LOGI("display", "Filling screen CYAN");
          it.fill(Color(0, 255, 255));  // Cyan (Green + Blue)
          break;
        case 6:
          ESP_LOGI("display", "Filling screen WHITE");
          it.fill(Color(255, 255, 255)); // White
          break;
        case 7:
          ESP_LOGI("display", "Filling screen BLACK");
          it.fill(Color(0, 0, 0));      // Black
          break;
      }
      color_phase++;

# GT911 Touchscreen (standard ESPHome component)
touchscreen:
  - platform: gt911
    interrupt_pin: 18
    reset_pin: 38
    on_touch:
      - lambda: |-
          ESP_LOGI("touch", "Touch detected at (%d, %d)", touch.x, touch.y);

# Fonts for display
font:
  - file: "gfonts://Roboto"
    id: font_small
    size: 16
  - file: "gfonts://Roboto"
    id: font_medium 
    size: 20
  - file: "gfonts://Roboto"
    id: font_large
    size: 28

# Sensors for monitoring
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime" 
    update_interval: 60s

  - platform: internal_temperature
    name: "ESP Temperature"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Device Status"

button:
  - platform: restart
    name: "Restart Device"
    
  - platform: safe_mode
    name: "Safe Mode"

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Pacific/Auckland"