esphome:
  name: viewe-display-7inch
  friendly_name: "VIEWE 7-inch Touch Display"
  includes:
    - include/
  platformio_options:
    build_flags:
      - "-DBOARD_HAS_PSRAM"
      - "-DLV_CONF_INCLUDE_SIMPLE"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_ESP32S3_SPIRAM_SUPPORT: "y"
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_SPIRAM_SPEED_80M: "y"
      CONFIG_ESP_MAIN_TASK_STACK_SIZE: "8192"
      CONFIG_LCD_ENABLE_DEBUG_LOG: "y"

logger:
  level: INFO
  logs:
    viewe_display: DEBUG

api:
  encryption:
    key: "your-32-char-encryption-key-here!!"

ota:
  - platform: esphome
    password: "your-ota-password-here"

wifi:
  ssid: "Your-WiFi-SSID"
  password: "Your-WiFi-Password"
  ap:
    ssid: "VIEWE Display Fallback"
    password: "fallback123"

captive_portal:

web_server:
  port: 80

# Use the external custom component
external_components:
  - source:
      type: local
      path: components
    components: [viewe_display]

# VIEWE Display with RGB LCD and GT911 touch
display:
  - platform: viewe_display
    id: main_display
    lambda: |-
      // Custom drawing can be added here if needed
      // This will be called for each frame
      // Use LVGL functions to create your UI instead

# Basic sensors for monitoring
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    update_interval: 60s

  - platform: internal_temperature
    name: "ESP Temperature"
    update_interval: 60s

binary_sensor:
  - platform: status
    name: "Device Status"

button:
  - platform: restart
    name: "Restart Device"
    
  - platform: safe_mode
    name: "Safe Mode"

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Pacific/Auckland"